/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function treeShake(input: string, preset: 'safest' | 'recommended' | 'smallest' | 'disabled', minify: boolean): TreeShakeResultBinding
export interface TreeShakeEntryResultBinding {
  output: Record<string, string>
  diagnostics: Array<string>
}
export declare function treeShakeEntry(entryPath: string, preset: 'safest' | 'recommended' | 'smallest' | 'disabled', minify: boolean): TreeShakeEntryResultBinding
export declare class TreeShakeResultBinding {
  output: string
  diagnostics: Array<string>
}
