/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MultiModuleResult {
  output: Record<string, string>
  diagnostics: Array<string>
}

export interface Options {
  preset?: 'safest' | 'recommended' | 'smallest' | 'disabled'
  minify?: boolean
  alwaysInlineLiteral?: boolean
}

export declare function shakeMultiModule(entryPath: string, options: Options): MultiModuleResult

export declare function shakeSingleModule(sourceText: string, options: Options): SingleModuleResult

export interface SingleModuleResult {
  output: string
  diagnostics: Array<string>
}
