/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Chunk {
  code: string
  sourceMapJson?: string
}

export interface MultiModuleResult {
  output: Record<string, Chunk>
  diagnostics: Array<string>
}

export interface Options {
  preset?: 'safest' | 'recommended' | 'smallest' | 'disabled'
  minify?: boolean
  alwaysInlineLiteral?: boolean
  jsx?: 'react'
  sourceMap?: boolean
}

export declare function shakeFsModule(entryPath: string, options: Options): MultiModuleResult

export declare function shakeMultiModule(sources: Record<string, string>, entry: string, options: Options): MultiModuleResult

export declare function shakeSingleModule(sourceText: string, options: Options): SingleModuleResult

export interface SingleModuleResult {
  output: Chunk
  diagnostics: Array<string>
}
